/**
 * The Photoshop templates an author paints a component's face in.
 *
 * Linked rather than bundled. The two come to nearly two megabytes, `public/`
 * ships verbatim into the build, and this is a file you open once in Photoshop
 * and never again — carrying it into every install to save one download is the
 * wrong trade for an app that is otherwise careful about what it embeds.
 *
 * The sources live in `assets/resources/` and are generated by `tools/`, so a
 * link here has to be re-uploaded when the geometry it draws its guides from
 * moves. That is the cost of this arrangement and it is worth naming: a stale
 * template is worse than none, because its guides look authoritative.
 */
export interface SkinTemplate {
  /** What the file is for, in the words the panel uses. */
  readonly label: string;
  readonly url: string;
}

/** The dial's face: one square, the disc inscribed in it. */
export const HEALTH_DIAL_SKIN: SkinTemplate = {
  label: 'Health dial skin (.psd)',
  url: 'https://drive.google.com/file/d/10Jni01h8Gne933BVXtJI_JhNpNQkNipK/view?usp=sharing'
};

/**
 * The dial's two faces, side by side, for the two-sided wrap — the same
 * front|back layout `TOKEN_SKIN` uses, with the front half carrying the same
 * health-number and trigger guide `HEALTH_DIAL_SKIN` does (the counter is
 * only ever drawn on the disc's front — see `health-dial.ts`) and the back
 * half a plain disc guide.
 *
 * A second file rather than the one `HEALTH_DIAL_SKIN` restructured to be
 * 2:1: a one-sided dial's reference image is still a plain square, fit
 * straight into `buildTokenTexture`, and forcing that author to work in a 2:1
 * canvas and crop it down would be a regression for the case that stays most
 * sets' only one. `tools/health-dial-skin.py` generates both from one set of
 * numbers, so the two guides cannot drift apart from each other.
 *
 */
export const HEALTH_DIAL_SKIN_TWO_SIDED: SkinTemplate = {
  label: 'Two-sided health dial skin (.psd)',
  url: 'https://drive.google.com/file/d/1LbkTM19C8uNv3pT0IGfTaz7Em8Y1CmKU/view?usp=sharing'
};

/** A token's two faces, side by side, for the two-sided wrap. */
export const TOKEN_SKIN: SkinTemplate = {
  label: 'Two-sided token skin (.psd)',
  url: 'https://drive.google.com/file/d/1UgqPluWhuPsjFYZPlKqdQD-gUW9MDL41/view?usp=sharing'
};
