/**
 * The Photoshop templates an author paints a component's face in.
 *
 * These are linked rather than bundled because they are large files someone
 * opens once in an image editor. Sources stay in `assets/resources/` and are
 * generated by `tools/`.
 */
export interface SkinTemplate {
  /** What the file is for, in the words the panel uses. */
  readonly label: string;
  readonly url: string;
}

/**
 * The fixed dial's complete 1:2 portrait UV atlas. Keep the local source and
 * hosted copy in step because its guides are tied to the supplied mesh's UVs.
 */
export const HEALTH_DIAL_SKIN_TWO_SIDED: SkinTemplate = {
  label: 'Health Dial Template (.psd)',
  url: 'https://drive.google.com/file/d/1BVn2AJhSJNIGTlDjdsK7rSucYW7-d-Nz/view?usp=drive_link'
};

/** A token's two faces, side by side, for the two-sided wrap. */
export const TOKEN_SKIN: SkinTemplate = {
  label: 'Two-sided token skin (.psd)',
  url: 'https://drive.google.com/file/d/1UgqPluWhuPsjFYZPlKqdQD-gUW9MDL41/view?usp=sharing'
};
