/**
 * The Photoshop templates an author paints a component's face in.
 *
 * Linked rather than bundled. The two come to nearly two megabytes, `public/`
 * ships verbatim into the build, and this is a file you open once in Photoshop
 * and never again — carrying it into every install to save one download is the
 * wrong trade for an app that is otherwise careful about what it embeds.
 *
 * The sources live in `assets/resources/` and are generated by `tools/`, so a
 * link here has to be re-uploaded when the geometry it draws its guides from
 * moves. That is the cost of this arrangement and it is worth naming: a stale
 * template is worse than none, because its guides look authoritative.
 */
export interface SkinTemplate {
  /** What the file is for, in the words the panel uses. */
  readonly label: string;
  readonly url: string;
}

/** The dial's face: one square, the disc inscribed in it. */
export const HEALTH_DIAL_SKIN: SkinTemplate = {
  label: 'Health dial skin (.psd)',
  url: 'https://drive.google.com/file/d/10Jni01h8Gne933BVXtJI_JhNpNQkNipK/view?usp=sharing'
};

/** A token's two faces, side by side, for the two-sided wrap. */
export const TOKEN_SKIN: SkinTemplate = {
  label: 'Two-sided token skin (.psd)',
  url: 'https://drive.google.com/file/d/1UgqPluWhuPsjFYZPlKqdQD-gUW9MDL41/view?usp=sharing'
};
